config/routes.rb
Todos::Application.routes.draw do
  root 'todos#index'
  resources :todos

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_todos
  has_many :todos, through: :tag_todos
end

app/models/tag_todo.rb
class TagTodo < ActiveRecord::Base
  belongs_to :tag
  belongs_to :todo
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  has_many :tag_todos
  has_many :tags, through: :tag_todos

#   validates_presence_of :do_what
  validates :do_what, presence: true

  def display_text
    if tags.blank?
      do_what
    elsif tags.count <= 4
      do_what + " (" + display_tags + ")"
    else
      do_what + " (" + display_tags + ", more...)"
    end
  end

  private

  def display_tags
    "#{show_tag_or_tags}: #{tags.first(4).map(&:name).join(", ")}"
  end

  def show_tag_or_tags
    if tags.count > 1
      "tags"
    else
      "tag"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user, only:[:create]

  def new
    @user = User.new
  end

  def create
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    elsif
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find_by(name: params[:name])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
  before_action :set_todo, only: [:edit, :show, :update, :destroy]
  
  def index
    @todos = Todo.all    
  end
  
  def new
    @todo = Todo.new
  
  end
  
  def create
    @todo = Todo.create(todo_param) 
    if @todo.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit; end

  def update
    if @todo.update(todo_param)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to root_path   
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  private
  
  def todo_param
    params.require(:todo).permit(:do_what)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "root", root_path, :class => 'brand' %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/todos/_form.html.haml
= form_for @todo do |f|
  = f.text_field :do_what
  = f.submit

app/views/todos/edit.html.haml
= render "form"

app/views/todos/index.html.haml
%h1= raw "Todo List #{link_to "new", new_todo_path}"
- @todos.each do |todo|
  %p= raw "#{todo.display_text}  #{link_to "edit", edit_todo_path(todo)} #{link_to "delete", todo_path(todo), method: :delete}"

app/views/todos/new.html.haml
=render 'form'